<?xml version="1.0" encoding="UTF-8" ?>
<testsuite failures="1" time="0.391" errors="15" skipped="0" tests="16" name="com.web.gearz.services.FilingServiceTest">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries"/>
    <property name="java.vm.version" value="17.1-b03-307"/>
    <property name="awt.nativeDoubleBuffering" value="true"/>
    <property name="gopherProxySet" value="false"/>
    <property name="mrj.build" value="10M3261"/>
    <property name="java.vm.vendor" value="Apple Inc."/>
    <property name="java.vendor.url" value="http://www.apple.com/"/>
    <property name="path.separator" value=":"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/Users/admin/repo_wg/GearzOfWeb"/>
    <property name="java.runtime.version" value="1.6.0_22-b04-307-10M3261"/>
    <property name="java.awt.graphicsenv" value="apple.awt.CGraphicsEnvironment"/>
    <property name="basedir" value="/Users/admin/repo_wg/GearzOfWeb"/>
    <property name="java.endorsed.dirs" value="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/endorsed"/>
    <property name="os.arch" value="x86_64"/>
    <property name="surefire.real.class.path" value="/var/folders/97/97ui+MkNGQmTwXxLC0OgnE+++TM/-Tmp-/surefirebooter3850258940744922759.jar"/>
    <property name="java.io.tmpdir" value="/var/folders/97/97ui+MkNGQmTwXxLC0OgnE+++TM/-Tmp-/"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Sun Microsystems Inc."/>
    <property name="os.name" value="Mac OS X"/>
    <property name="sun.jnu.encoding" value="MacRoman"/>
    <property name="java.library.path" value=".:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"/>
    <property name="surefire.test.class.path" value="/Users/admin/repo_wg/GearzOfWeb/target/test-classes:/Users/admin/repo_wg/GearzOfWeb/target/classes:/Users/admin/.m2/repository/org/springframework/spring-context/3.0.4.RELEASE/spring-context-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-aop/3.0.4.RELEASE/spring-aop-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/admin/.m2/repository/org/springframework/spring-asm/3.0.4.RELEASE/spring-asm-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-beans/3.0.4.RELEASE/spring-beans-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-core/3.0.4.RELEASE/spring-core-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-expression/3.0.4.RELEASE/spring-expression-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-webmvc/3.0.4.RELEASE/spring-webmvc-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-context-support/3.0.4.RELEASE/spring-context-support-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-web/3.0.4.RELEASE/spring-web-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/roo/org.springframework.roo.annotations/1.0.2.RELEASE/org.springframework.roo.annotations-1.0.2.RELEASE.jar:/Users/admin/.m2/repository/org/aspectj/aspectjrt/1.6.9/aspectjrt-1.6.9.jar:/Users/admin/.m2/repository/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar:/Users/admin/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.10/jcl-over-slf4j-1.5.10.jar:/Users/admin/.m2/repository/org/slf4j/slf4j-log4j12/1.5.10/slf4j-log4j12-1.5.10.jar:/Users/admin/.m2/repository/log4j/log4j/1.2.15/log4j-1.2.15.jar:/Users/admin/.m2/repository/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar:/Users/admin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/admin/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar:/Users/admin/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar:/Users/admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar:/Users/admin/.m2/repository/org/mongodb/mongo-java-driver/1.3/mongo-java-driver-1.3.jar:/Users/admin/.m2/repository/junit/junit/4.7/junit-4.7.jar:/Users/admin/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/Users/admin/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="50.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Server Compiler"/>
    <property name="os.version" value="10.6.6"/>
    <property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="user.home" value="/Users/admin"/>
    <property name="user.timezone" value=""/>
    <property name="java.awt.printerjob" value="apple.awt.CPrinterJob"/>
    <property name="java.specification.version" value="1.6"/>
    <property name="file.encoding" value="MacRoman"/>
    <property name="user.name" value="admin"/>
    <property name="java.class.path" value="/Users/admin/repo_wg/GearzOfWeb/target/test-classes:/Users/admin/repo_wg/GearzOfWeb/target/classes:/Users/admin/.m2/repository/org/springframework/spring-context/3.0.4.RELEASE/spring-context-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-aop/3.0.4.RELEASE/spring-aop-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/admin/.m2/repository/org/springframework/spring-asm/3.0.4.RELEASE/spring-asm-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-beans/3.0.4.RELEASE/spring-beans-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-core/3.0.4.RELEASE/spring-core-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-expression/3.0.4.RELEASE/spring-expression-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-webmvc/3.0.4.RELEASE/spring-webmvc-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-context-support/3.0.4.RELEASE/spring-context-support-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/spring-web/3.0.4.RELEASE/spring-web-3.0.4.RELEASE.jar:/Users/admin/.m2/repository/org/springframework/roo/org.springframework.roo.annotations/1.0.2.RELEASE/org.springframework.roo.annotations-1.0.2.RELEASE.jar:/Users/admin/.m2/repository/org/aspectj/aspectjrt/1.6.9/aspectjrt-1.6.9.jar:/Users/admin/.m2/repository/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar:/Users/admin/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.10/jcl-over-slf4j-1.5.10.jar:/Users/admin/.m2/repository/org/slf4j/slf4j-log4j12/1.5.10/slf4j-log4j12-1.5.10.jar:/Users/admin/.m2/repository/log4j/log4j/1.2.15/log4j-1.2.15.jar:/Users/admin/.m2/repository/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar:/Users/admin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/admin/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar:/Users/admin/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar:/Users/admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar:/Users/admin/.m2/repository/org/mongodb/mongo-java-driver/1.3/mongo-java-driver-1.3.jar:/Users/admin/.m2/repository/junit/junit/4.7/junit-4.7.jar:/Users/admin/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/Users/admin/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:"/>
    <property name="java.vm.specification.version" value="1.0"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"/>
    <property name="java.specification.vendor" value="Sun Microsystems Inc."/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="apple.awt.CToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.6.0_22"/>
    <property name="java.ext.dirs" value="/Library/Java/Extensions:/System/Library/Java/Extensions:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext"/>
    <property name="sun.boot.class.path" value="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsfd.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar:/System/Library/Frameworks/JavaVM.framework/Frameworks/JavaRuntimeSupport.framework/Resources/Java/JavaRuntimeSupport.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/ui.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/laf.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/sunrsasign.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsse.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jce.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/charsets.jar"/>
    <property name="java.vendor" value="Apple Inc."/>
    <property name="localRepository" value="/Users/admin/.m2/repository"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.apple.com/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="mrj.version" value="1060.1.6.0_22-307"/>
    <property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase time="0.319" classname="com.web.gearz.services.FilingServiceTest" name="shouldConnectToLocal">
    <failure message="null" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.web.gearz.services.FilingServiceTest.shouldConnectToLocal(FilingServiceTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
</failure>
    <system-err>com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.storeContent(FilingService.java:63)
	at com.web.gearz.services.FilingServiceTest.shouldConnectToLocal(FilingServiceTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more
</system-err>
  </testcase>
  <testcase time="0.324" classname="com.web.gearz.services.FilingServiceTest" name="shouldConnectToLocal">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
    <system-err>com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.storeContent(FilingService.java:63)
	at com.web.gearz.services.FilingServiceTest.shouldConnectToLocal(FilingServiceTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more
</system-err>
  </testcase>
  <testcase time="0.001" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddNewObject">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddNewObject(FilingServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddNewObject">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.002" classname="com.web.gearz.services.FilingServiceTest" name="shouldUpdateExistingObject">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldUpdateExistingObject(FilingServiceTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldUpdateExistingObject">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.001" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject2">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject2(FilingServiceTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject2">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.001" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject3">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject3(FilingServiceTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject3">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.001" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject4">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject4(FilingServiceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldAddObject4">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.001" classname="com.web.gearz.services.FilingServiceTest" name="shouldRetrieveDefaultText">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.getContent(FilingService.java:82)
	at com.web.gearz.services.FilingServiceTest.shouldRetrieveDefaultText(FilingServiceTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldRetrieveDefaultText">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
  <testcase time="0.002" classname="com.web.gearz.services.FilingServiceTest" name="shouldRetrieveStoredContent">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.storeContent(FilingService.java:63)
	at com.web.gearz.services.FilingServiceTest.shouldRetrieveStoredContent(FilingServiceTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more
</error>
  </testcase>
  <testcase time="0.003" classname="com.web.gearz.services.FilingServiceTest" name="shouldRetrieveStoredContent">
    <error message="can&apos;t call something" type="com.mongodb.MongoException$Network">com.mongodb.MongoException$Network: can&apos;t call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn&apos;t connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more
</error>
  </testcase>
</testsuite>